# Generated by Django 3.2.13 on 2022-07-26 22:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('recipes', '0002_recipebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover_pic', models.CharField(max_length=255)),
                ('total_calories', models.FloatField(default=0)),
                ('rate', models.FloatField(default=1)),
                ('methods', models.CharField(max_length=1024)),
                ('cooking_time', models.FloatField()),
                ('keywords', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredients')),
                ('recipebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
