# Generated by Django 3.2.13 on 2022-07-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipes',
            table='recipes',
        ),
    ]
